spring:
  application:
    name: library-management-system

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

app:
  auth:
    tokenSecret: ${JWT_SECRET}
    tokenExpiry: ${JWT_EXPIRATION_DURATION}
